"""
alerts.py
Sends alert emails via SMTP (no third-party API required).

Farmer alert  – general quarantine / disease-spread advisory.
Vet alert     – interactive Google Maps heatmap with 4 risk zones:
                  • red    zone:  0–5  km  (critical)
                  • orange zone:  5–15 km  (high)
                  • yellow zone: 15–25 km  (moderate)
                  • blue   zone: 25–35 km  (low)
"""

import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

log = logging.getLogger(__name__)

SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER     = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL    = os.getenv("ALERT_FROM_EMAIL", SMTP_USER)
MAPS_API_KEY  = os.getenv("GOOGLE_MAPS_API_KEY", "YOUR_MAPS_KEY")


# ── Internal sender ───────────────────────────────────────────────────────────

def _send(to_email: str, subject: str, html_body: str) -> bool:
    if not SMTP_USER or not SMTP_PASSWORD:
        log.warning("SMTP credentials not configured – skipping.")
        return False
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = FROM_EMAIL
        msg["To"]      = to_email
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(FROM_EMAIL, to_email, msg.as_string())

        log.info("Email sent to %s", to_email)
        return True
    except smtplib.SMTPAuthenticationError:
        log.error("SMTP auth failed.")
    except smtplib.SMTPException as exc:
        log.error("SMTP error for %s: %s", to_email, exc)
    except Exception as exc:
        log.error("Unexpected error for %s: %s", to_email, exc)
    return False


# ── Farmer alert ──────────────────────────────────────────────────────────────

FARMER_SUBJECT = "DuckTrack Disease Alert – Immediate Action Required"

FARMER_HTML_TEMPLATE = """\
<html>
<body style="font-family: Arial, sans-serif; color: #333333; max-width: 600px; margin: auto; background-color: #ffffff; padding: 0;">
  <div style="background-color: #c0392b; padding: 20px; text-align: left;">
    <h2 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: bold; font-family: Arial, sans-serif;">DuckTrack Disease Alert</h2>
  </div>
  <div style="padding: 24px; background-color: #ffffff; border: 1px solid #dddddd; border-top: none;">
    <p style="margin-top: 0; font-size: 15px; line-height: 1.5;">Dear {name},</p>
    
    <p style="font-size: 15px; line-height: 1.5;">
      A duck disease has been reported near your registered area (PIN: {pin_code}).
      This notification is being sent to farmers in the surrounding region so that preventive measures can be taken early.
    </p>

    <h3 style="color: #333333; font-size: 16px; font-weight: bold; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid #eeeeee; padding-bottom: 6px;">Recommended actions:</h3>
    <ul style="line-height: 1.8; font-size: 15px; padding-left: 20px; margin-top: 0; margin-bottom: 24px; list-style-type: disc;">
      <li>Isolate your flock and restrict movement of ducks</li>
      <li>Contact the nearest veterinary officer if symptoms appear</li>
      <li>Avoid selling or transporting ducks temporarily</li>
      <li>Maintain strict hygiene in sheds and water sources</li>
      <li>Monitor ducks for unusual symptoms or mortality</li>
    </ul>

    <h3 style="color: #333333; font-size: 16px; font-weight: bold; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid #eeeeee; padding-bottom: 6px;">Detection Location</h3>
    <table style="font-size: 15px; line-height: 1.6; border-collapse: collapse; margin-bottom: 24px;">
      <tr>
        <td style="padding: 2px 16px 2px 0; color: #666666; font-weight: bold;">Latitude:</td>
        <td style="color: #333333;">{latitude}</td>
      </tr>
      <tr>
        <td style="padding: 2px 16px 2px 0; color: #666666; font-weight: bold;">Longitude:</td>
        <td style="color: #333333;">{longitude}</td>
      </tr>
      <tr>
        <td style="padding: 2px 16px 2px 0; color: #666666; font-weight: bold;">PIN Code:</td>
        <td style="color: #333333;">{pin_code}</td>
      </tr>
    </table>

    <hr style="border: 0; border-top: 1px solid #dddddd; margin: 24px 0;" />

    <p style="color: #777777; font-size: 12px; line-height: 1.5; margin: 0;">
      This is an automated alert generated by the DuckTrack monitoring system.<br />
      Please do not reply to this email.
    </p>
  </div>
</body>
</html>
"""


def send_farmer_alert(
    farmer_email: str,
    farmer_name:  str,
    latitude:     float,
    longitude:    float,
    pin_code:     str,
) -> bool:
    html = FARMER_HTML_TEMPLATE.format(
        name      = farmer_name,
        pin_code  = pin_code,
        latitude  = latitude,
        longitude = longitude,
    )
    return _send(farmer_email, FARMER_SUBJECT, html)


# ── Veterinary alert ──────────────────────────────────────────────────────────

VET_SUBJECT = "DuckTrack Vet Alert – Disease Outbreak Heat Map"

VET_HTML_TEMPLATE = """\
<html>
<head>
<style>
  body {{ font-family: Arial, sans-serif; color: #333333; max-width: 650px; margin: auto; background-color: #ffffff; padding: 0; }}
  .header {{ background-color: #c0392b; padding: 20px; text-align: left; }}
  .header h2 {{ color: #ffffff; margin: 0; font-size: 20px; font-weight: bold; }}
  .content {{ padding: 24px; background-color: #ffffff; border: 1px solid #dddddd; border-top: none; }}
  .section-title {{ color: #333333; font-size: 16px; font-weight: bold; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid #eeeeee; padding-bottom: 6px; }}
  .info-table {{ font-size: 15px; line-height: 1.6; border-collapse: collapse; margin-bottom: 24px; }}
  .info-label {{ padding: 2px 16px 2px 0; color: #666666; font-weight: bold; }}
  .info-value {{ color: #333333; }}
  .legend {{ display: flex; flex-direction: column; gap: 8px; margin: 16px 0; padding: 0; list-style: none; }}
  .legend-item {{ display: flex; align-items: center; gap: 10px; font-size: 14px; color: #333333; }}
  .dot {{ width: 12px; height: 12px; border-radius: 50%; flex-shrink: 0; }}
  .map-wrap {{ border: 1px solid #dddddd; border-radius: 8px; overflow: hidden; margin: 20px 0; }}
  .btn {{ display: inline-block; background-color: #c0392b; color: #ffffff; padding: 10px 20px;
          border-radius: 4px; text-decoration: none; font-size: 14px; font-weight: bold; margin-top: 8px; }}
</style>
</head>
<body>

  <div class="header">
    <h2>DuckTrack Disease Alert</h2>
  </div>

  <div class="content">
    <p style="margin-top: 0; font-size: 15px; line-height: 1.5;">Dear Dr. {name},</p>
    
    <p style="font-size: 15px; line-height: 1.5;">
      A duck disease outbreak has been detected. The map below shows the outbreak location and surrounding risk zones.
    </p>

    <div class="section-title">Detection Location</div>
    <table class="info-table">
      <tr>
        <td class="info-label">Latitude:</td>
        <td class="info-value">{latitude}</td>
      </tr>
      <tr>
        <td class="info-label">Longitude:</td>
        <td class="info-value">{longitude}</td>
      </tr>
      <tr>
        <td class="info-label">PIN Code:</td>
        <td class="info-value">{pin_code}</td>
      </tr>
    </table>

    <div class="section-title">Risk Zone Legend</div>
    <ul class="legend">
      <li class="legend-item"><div class="dot" style="background-color: #ff0000;"></div> Critical Risk (0–5 km)</li>
      <li class="legend-item"><div class="dot" style="background-color: #ff8c00;"></div> High Risk (5–15 km)</li>
      <li class="legend-item"><div class="dot" style="background-color: #ffd700;"></div> Moderate Risk (15–25 km)</li>
      <li class="legend-item"><div class="dot" style="background-color: #1a73e8;"></div> Low Risk (25–35 km)</li>
    </ul>

    <!-- Static Google Maps embed centred on outbreak site -->
    <div class="map-wrap">
      <iframe
        width="100%" height="420" style="border:0;" loading="lazy" allowfullscreen
        src="https://www.google.com/maps/embed/v1/view?key={maps_api_key}&center={latitude},{longitude}&zoom=10">
      </iframe>
    </div>

    <a class="btn"
       href="https://www.google.com/maps/search/?api=1&query={latitude},{longitude}"
       target="_blank">
      Open in Google Maps
    </a>

    <!--
      NOTE: Google Maps JS API scripts are blocked in most email clients.
      The interactive circle overlay below works only when this email is opened
      in a browser (e.g. via "View in browser" link). For production consider
      generating a pre-rendered static map image using the Maps Static API.
    -->
    <div id="js-map" style="height:420px;width:100%;border:1px solid #dddddd;border-radius:8px;margin-top:20px;display:none;"></div>
    <script>
      document.getElementById('js-map').style.display = 'block';
      function initMap() {{
        const centre = {{ lat: {latitude}, lng: {longitude} }};
        const map = new google.maps.Map(document.getElementById('js-map'), {{
          center: centre, zoom: 10
        }});
        [
          {{ radius:  5000, color: '#ff0000', opacity: 0.20 }},
          {{ radius: 15000, color: '#ff8c00', opacity: 0.18 }},
          {{ radius: 25000, color: '#ffd700', opacity: 0.16 }},
          {{ radius: 35000, color: '#1a73e8', opacity: 0.14 }},
        ].forEach(z => new google.maps.Circle({{
          map, center: centre,
          radius:        z.radius,
          strokeColor:   z.color,
          strokeOpacity: 0.85,
          strokeWeight:  2,
          fillColor:     z.color,
          fillOpacity:   z.opacity,
        }}));
        new google.maps.Marker({{ position: centre, map,
          title: 'Outbreak site',
          icon: {{ path: google.maps.SymbolPath.CIRCLE,
                   scale: 8, fillColor:'#ff0000',
                   fillOpacity:1, strokeWeight:2, strokeColor:'#fff' }} }});
      }}
    </script>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key={maps_api_key}&callback=initMap">
    </script>

    <hr style="border: 0; border-top: 1px solid #dddddd; margin: 24px 0;" />

    <p style="color: #777777; font-size: 12px; line-height: 1.5; margin: 0;">
      This is an automated alert generated by the DuckTrack monitoring system.<br />
      Please do not reply to this email.
    </p>
  </div>
</body>
</html>
"""


def send_vet_alert(
    vet_email:  str,
    vet_name:   str,
    latitude:   float,
    longitude:  float,
    pin_code:   str,
) -> bool:
    html = VET_HTML_TEMPLATE.format(
        name         = vet_name,
        latitude     = latitude,
        longitude    = longitude,
        pin_code     = pin_code,
        maps_api_key = MAPS_API_KEY,
    )
    return _send(vet_email, VET_SUBJECT, html)