"use client";

import { Message } from "./types";
import { Bot, User } from "lucide-react";

export default function MessageBubble({ message }: { message: Message }) {
  const isUser = message.sender === "user";

  return (
    <div className={`flex w-full ${isUser ? "justify-end" : "justify-start"} animate-in fade-in slide-in-from-bottom-2`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] gap-2 lg:gap-3 ${isUser ? "flex-row-reverse" : "flex-row"}`}>
        
        {/* Avatar */}
        <div className={`w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center mt-1 shadow-sm ${
          isUser 
            ? "bg-slate-800 text-white dark:bg-slate-100 dark:text-slate-900" 
            : "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/50 dark:text-emerald-400"
        }`}>
          {isUser ? <User className="w-4 h-4" /> : <Bot className="w-5 h-5" />}
        </div>

        {/* Message Bubble */}
        <div className={`px-4 py-3 text-sm md:text-base leading-relaxed shadow-sm ${
          isUser 
            ? "bg-slate-800 text-white dark:bg-slate-100 dark:text-slate-900 rounded-2xl rounded-tr-sm" 
            : "bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 rounded-2xl rounded-tl-sm"
        }`}>
          {/* Support basic markdown for bold text (often generated by Gemini) */}
          <div 
             className="whitespace-pre-wrap break-words" 
             dangerouslySetInnerHTML={{ 
               __html: message.text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
             }} 
          />
        </div>
      </div>
    </div>
  );
}
